# vim:ft=ruby

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, :path => 'provision.sh'
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id,
                  "--memory", 2048,
                  "--cpus", 2,
                  "--natdnshostresolver1", "on",
                  "--natdnsproxy1", "on"]
  end

  config.vm.define :slave2 do |cfg|
    cfg.vm.hostname = "slave2"
    cfg.vm.network "private_network", ip: '33.33.33.102', type: 'static'
  end
end